version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps):"

  - package-ecosystem: "npm"
    directory: "/src/create-key-pair"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps):"
